# Project
version=10.0.0+1.21.4
group=com.illusivesoulworks.elytraslot
java_version=21

# Common
minecraft_version=1.21.4
mod_name=Elytra Slot
mod_author=Illusive Soulworks
mod_id=elytraslot
license=LGPL-3.0-or-later
issues_url=https://github.com/illusivesoulworks/elytraslot/issues
sources_url=https://github.com/illusivesoulworks/elytraslot
description=Adds an accessory slot for the elytra, so you can fly and wear chest armor at the same time.
minecraft_version_range=[1.21.4, 1.22)
minecraft_version_range_alt=~1.21.4

## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.4-20241203.161809

# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_mc=1.21.4
parchment_version=2025.03.23

# Fabric
fabric_version=0.113.0+1.21.4
fabric_loader_version=0.16.9

# Fabric Dependencies
trinkets_version=3.10.0
accessories_version=1.2.19-beta+1.21.4
mod_menu_version=13.0.3

# NeoForge
neoforge_version=21.4.136
neoforge_version_range=[21.4.123,)

# NeoForge Dependencies
curios_version=10.0.1+1.21.4
curios_version_range=[7.0.0,)
caelus_version=8.0.0+1.21.4
caelus_version_range=[7.0.0,)
mccapes_cf_file_id=5966373

# CurseForge Options
cf_id=317716
cf_page=https://www.curseforge.com/minecraft/mc-mods/elytra-slot
modrinth_id=mSQF1NpT
modrinth_page=https://modrinth.com/mod/elytra-slot
release_type=release
release_versions=1.21.4
changelog_link=https://github.com/illusivesoulworks/elytraslot/blob/1.21.4/CHANGELOG.md
discord_thumbnail=https://media.forgecdn.net/avatars/209/40/636979175379460863.png

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
